_schema: _schema
paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: content
    name: Pages
    icon: wysiwyg
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  blog:
    path: content/blog
    name: Blog
    icon: event_available
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: America/New_York
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
